name: "typescript action template"
description: "Example GitHub Action written in TypeScript"
branding:
  icon: "book-open"
  color: "white"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  message: # id of output
    description: "The greeting"
runs:
  using: "node20"
  main: "dist/index.js"
